config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'
  resources :categories do
    resources :trainings, only:[:index, :create, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :trainings
  validates :name, presence: true, length: { maximum: 25 }
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :category
  validates :content, presence: true, length: { maximum: 25 }
  validates :time, presence: true
  
  ransacker :created_at, callable: proc { Arel.sql('DATE(created_at)') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
     @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
    @training = Training.new
    
    # --------Ransack用アクション--------
    @search = @category.trainings.ransack(params[:q])
    @search_trainings = 
    @search.result(distinct: true)
    # -----------------------------------
    
    # --------当日の投稿内容表示--------
    @trainings = @category.trainings.where(date: Time.current.all_day)
    # ----------------------------------

    #--------「xx年xx月xx日」の計算--------
      @training_day = Date.current
    #--------------------------------------
    
    # --------本日の合計時間--------
    ss = 0
    @trainings.each do |train|
      s = train.time
      ss += s
    end
    @today_total_hour = ss / 60
    @today_total_min = ss % 60
    # ------------------------------
    
    # --------トータルの合計時間--------
    @total_trainings = @category.trainings.all
    uu = 0
    @total_trainings.each do |total_train|
      u = total_train.time
      uu += u
    end
    @all_total_hour = uu / 60
    @all_total_min = uu % 60
    # ----------------------------------
    
    # --------今月の合計時間--------
    @month_trainings = @category.trainings.where(created_at: Time.current.all_month)
    vv = 0
    @month_trainings.each do |month_train|
      v = month_train.time
      vv += v
    end
    @month_total_hour = vv / 60
    @month_total_min = vv % 60
    # ------------------------------
    
    @search_category = Category.find(params[:id])
    @search = @search_category.trainings.ransack(params[:q])
    @search_trainings = @search.result
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Create new category!"
      redirect_to root_url
    else
      flash[:danger] = "Failed..."
      render :new
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Edit category!"
      redirect_to @category
    else
      flash[:danger] = "Failed..."
      render :edit
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.delete
    flash[:success] = "Delete category!"
    redirect_to root_url
  end
  
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @search = @category.trainings.ransack(params[:q])

    @search_trainings = 
      if params[:q].blank?
        Training.none.search
      else  
        @search.result(distinct: true)
      end
  end

  def show
    @category = Category.find(params[:category_id])
    @training = @category.trainings.find(params[:id])
  end

  def create
    @training = Training.new(training_params)
    @category = Category.find(params[:category_id])
    @training.category_id = @category.id
    if @training.save
      flash[:success] = "Entry new training!"
      redirect_to @category
    else
      flash[:danger] = "Failed..."
      redirect_to @category
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @training = @category.trainings.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @training = @category.trainings.find(params[:id])
    if @training.update(training_params)
      flash[:success] = "Edit training!"
      redirect_to @category
    else
      flash[:danger] = "Failed..."
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @training = @category.trainings.find(params[:id])
    @training.delete
    flash[:success] = "Delete training!"
    redirect_to @category
  end
  
  
  private
  
  def training_params
    params.require(:training).permit(:content, :time, :date)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<div class="categories-new row">
    <div class="new-category-card col-10 mx-auto py-5 px-5">
        <h4 class="pb-4">Edit category name</h4>
        <div class="new-category-form mx-auto col-12">
            <%= form_with(model: @category, local: true) do |f| %>
                <%= f.text_field :name, class:"col-sm-7 col-9 no-gutters", :placeholder => "Category name" %>
                <%= f.submit 'edit', class:"col-sm-2 col-2 no-gutters" %>
            <% end %>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<div class="row categories-index">
    
    <% @categories.each do |category| %>
            <div class="category-card col-sm-8 mx-auto">
                <%= link_to category, class:"category_name" do %><%= category.name %><% end %>
            </div>
    <% end %>
<div class="new-category col-sm-8 mx-auto">
    <%= link_to new_category_path do %><i class="fas fa-folder-plus"></i><% end %>
</div>
</div>

app/views/categories/new.html.erb
<div class="categories-new row">
    <div class="new-category-card col-10 mx-auto py-5 px-5">
        <h4 class="pb-4">Create new category</h4>
        <div class="new-category-form mx-auto col-12">
            <%= form_with(model: @category, local: true) do |f| %>
                <%= f.text_field :name, class:"col-sm-7 col-9 no-gutters", :placeholder => "Category name" %>
                <%= f.submit 'add', class:"col-sm-2 col-2 no-gutters" %>
            <% end %>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<div class="row categories-show col-sm-12 mx-auto">
    
    <div class="categories-show-left col-sm-8">
        
        <!--タイトル表示--------------------------------------------------------------->
        <div class="title-card py-3 py-sm-4 mb-2 pr-4">
            <h3 class="date-title pl-sm-5 pl-4">
                <%= @category.name %> Log
            </h3>
                <%= link_to edit_category_url do %><i class="fas fa-edit"></i><% end %>
                <%= link_to @category, method: :delete, data: { confirm: "削除しますか?" } do %><i class="fas fa-trash"></i><% end %>
        </div>
        <!------------------------------------------------------------------------->
        
        <div class="form-and-list-card py-sm-5 pt-3 pb-4 mb-2">
        
            <!--Training入力フォーム--------------------------------------------------->
            <div class="training-form-card col-sm-11 mx-auto">
                <h3 class="pl-3 pb-sm-4"> on <%= @training_day %></h3>
                <%= form_with(model: [@category, @training], local: true) do |f| %>
                    <%= f.text_field :content, class:"col-7 no-gutters", :placeholder => "Training content" %>
                    <%= f.number_field :time, step: "10", class:"col-2 no-gutters", :placeholder => "min" %>
                    <%= f.hidden_field :date, :value => Date.current %>
                    <%= f.submit 'add', class:"col-2 no-gutters" %>
                <% end %>
            </div>
            <!------------------------------------------------------------------------->
    
            <!--今日のTraining一覧----------------------------------------------------->
            <div class="today-trainings-card col-12 pt-3">
                <% @trainings.each do |training| %>
                <div class="today-training py-2 col-sm-10 mx-auto row">
                    <div class="col-2"><%= link_to edit_category_training_path(@category, training) do %><i class="fas fa-check-square"></i><% end %></div>
                    <div class="col-7 no-gutters"><%= training.content %></div>
                    <div class="col-3"><%= training.time %>min</div>
                </div>
                <% end %>
            </div>
            <!------------------------------------------------------------------------->
            
        </div>

    </div>
    
    <div class="categories-show-right col-sm-4">
    
        <!--合計時間カード--------------------------------------------------------->
        <div class="today-total-card py-2 pl-4 py-sm-3 mb-2">
            <p>today &nbsp;&nbsp;: <%= @today_total_hour %>h.&nbsp;<%= @today_total_min %>min</p>
        </div>
        
        <div class="month-total-card py-2 pl-4 py-sm-3 mb-2">
            <p>month : <%= @month_total_hour %>h.&nbsp;<%= @month_total_min %>min</p>
        </div>
        
        <div class="all-total-card py-2 pl-4 py-sm-3 mb-2">
            <p>all &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <%= @all_total_hour %>h.&nbsp;<%= @all_total_min %>min</p>
        </div>
        <!------------------------------------------------------------------------->
        
        <!--Training検索フォーム--------------------------------------------------->
        <div class="seach-form-card pt-2 pb-3 pl-4 pt-sm-3 pb-sm-4 mb-2">
            <p>Search previous</p>
            <%= search_form_for @search, url: category_trainings_path(@category.id) do |f| %>
                <%= f.date_field :date_eq, :placeholder => "20XX-XX-XX", class:"col-9 no-gutters seach-button" %>
                <%= f.submit "find", class:"col-2 no-gutters" %>
            <% end %>
        </div>
        <!------------------------------------------------------------------------->
    
    </div>

</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar-all">
  <nav class="navbar navbar-expand-sm bg">
    <a class="navbar-brand" href="/">MyTrainingLog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Training Log</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/navbar' %>

      <div class="container pb-sm-5 pb-2">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>
    
      <footer>&copy; 2020 Teruya Sawamura All Right Reserved.</footer>
    </div>
  </body>
</html>

app/views/trainings/edit.html.erb
<div class="categories-new row">
    <div class="new-category-card col-10 mx-auto py-5 px-sm-5">
        <h4 class="pb-4">
            Edit training
            <span class="pr-sm-4"><%= link_to category_training_path(@category, @training), method: :delete, data: { confirm: "削除しますか?" } do %><i class="fas fa-trash"></i><% end %></span>
        </h4>
        <div class="new-category-form mx-auto col-12">
            <%= form_with(model: [@category, @training], local: true) do |f| %>
                <%= f.label :content, class:"col-sm-4 col-4 no-gutters" "Content" %>
                <%= f.text_field :content, class:"col-sm-7 col-7 no-gutters", :placeholder => "Training content" %>
                <%= f.label :time, class:"col-sm-4 col-4 no-gutters" "Minute" %>
                <%= f.number_field :time, step: "10", class:"col-sm-7 col-7 no-gutters", :placeholder => "min" %>
                <%= f.label :date, class:"col-sm-4 col-4 no-gutters" "Date" %>
                <%= f.date_field :date, class:"col-sm-7 col-7 no-gutters", :placeholder => "20XX-XX-XX" %>
                <div class="edit-training-btn pr-sm-4"><%= f.submit 'edit', class:"col-sm-5 col-11 no-gutters" %></div>
            <% end %>
        </div>
        <div class="back-link">
            <%= link_to 'back', category_path(@category) %>
        </div>
    </div>
</div>

app/views/trainings/index.html.erb
<div class="categories-new row">
    <div class="new-category-card col-10 mx-auto py-5 px-1">
        <h4 class="pb-4">Search training</h4>
        <div class="new-category-form mx-auto col-12">
            <%= search_form_for @search, url: "trainings#index"  do |f| %>
                <%= f.date_field :date_eq, class:"col-sm-7 col-9 no-gutters", :placeholder => "20XX-XX-XX" %>
                <%= f.submit 'searh', class:"col-sm-2 col-2 no-gutters" %>
            <% end %>
        </div>
  
        <div class="today-trainings-card mx-auto col-12 pt-4">
            <% @search_trainings.each do |search_training| %>
            <div class="today-training py-2 col-sm-10 mx-auto row">
                <div class="col-2"><%= link_to edit_category_training_path(@category, search_training) do %><i class="fas fa-check-square"></i><% end %></div>
                <div class="col-7 no-gutters"><%= search_training.content %></div>
                <div class="col-3"><%= search_training.time %>min</div>
            </div>
            <% end %>
        </div>
        
        <div class="back-link">
            <%= link_to 'back', category_path(@category), class:"" %>
        </div>
    </div>
</div>



    